#
#--------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------
#
# 藉由編輯 'php-fpm' 的基本映像檔；觀摩該 repo
#   https://github.com/Laradock/php-fpm
# 


ARG DEV_PHP_VERSION
ARG BASE_IMAGE_TAG_PREFIX=latest
FROM php:8.1-fpm-alpine3.16 

LABEL maintainer="samzheng <sam33339999@gmail.com>"



RUN set -xe; \
    apk add vim


